include ../../makefile.master
include ../makefile.langpair
DATASET=news
INPUT_SRC=../../../qtleap-corpus/references/news_en.txt
INPUT_REF=../../../qtleap-corpus/references/news_cs.txt

# ../makefile.langpair contains domain=IT, but we want to override it
SCEN=Scen::EN2CS domain=general resegment=1
