include ../../makefile.master
include ../makefile.langpair
INPUT_SRC=../../../qtleap-corpus/references/Batch1q_eu.txt
INPUT_REF=../../../qtleap-corpus/references/Batch1q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-eu-en-batch1q.txt
