include ../../makefile.master
include ../makefile.langpair
DATASET=news
INPUT_SRC=../../../qtleap-corpus/references/news_en.txt
INPUT_REF=../../../qtleap-corpus/references/news_es.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-es-news.txt

# ../makefile.langpair contains domain=IT, but we want to override it
SCEN=Scen::EN2ES domain=general resegment=1
