include ../../makefile.master
include ../makefile.langpair
INPUT_SRC=../../../qtleap-corpus/references/Batch2q_cs.txt
INPUT_REF=../../../qtleap-corpus/references/Batch2q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-cs-en-batch2q.txt
