include ../../makefile.master
include ../makefile.langpair
DATASET=batch3q
INPUT_SRC=../../../qtleap-corpus/references/Batch3q_cs.txt
INPUT_REF=../../../qtleap-corpus/references/Batch3q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-cs-en-batch3q.txt
