SHELL=/bin/bash
################ test data preparation ##################

TEST_DATA_STAGE=orig_plain
ifdef TEST_DATASET
TEST_DATA:=$(shell perl -e 'my $$a = { $(TEST_DATASET_HASH) }; print $$a->{$(TEST_DATASET)}; print "\n";')
TEST_DATA_STAGE:=$(shell perl -e 'my @a = grep {$$_ eq $$ARGV[1]} split /\s+/, $$ARGV[0]; print @a ? "segm" : "orig_plain"; print "\n";' "$(TEST_DATASET_IN_SGM)" $(TEST_DATASET))
endif

TEST_DATA_STEM=$(shell bin/para_data_stem.pl "$(TEST_DATA)")
TEST_TMP_DIR=tmp/$(TRANSL_PAIR)/$(TEST_DATA_STEM)

PREPARE_TEST_DATA_PARAMS=DATA="$(TEST_DATA)" STAGE=$(TEST_DATA_STAGE) LANG_PAIR=$(PARA_DATA_PAIR) TMP_DIR=tmp/$(PARA_DATA_PAIR)/$(TEST_DATA_STEM) SENTS_PER_DOC=11

LANG1_TEXT_SPLIT_LIST := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis plain_split_src_list $(PREPARE_TEST_DATA_PARAMS))
LANG2_TEXT_SPLIT_LIST := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis plain_split_trg_list $(PREPARE_TEST_DATA_PARAMS))

LANG1_SEGM_DATA := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis segm_src_data_path $(PREPARE_TEST_DATA_PARAMS))
LANG2_SEGM_DATA := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis segm_trg_data_path $(PREPARE_TEST_DATA_PARAMS))

ifeq ($(TEST_DATA_STAGE),orig_plain)
LANG1_PLAIN_PREPROC_DATA := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis filtered_plain_src_data_path $(PREPARE_TEST_DATA_PARAMS))
LANG2_PLAIN_PREPROC_DATA := $(shell $(MAKE) -s --no-print-directory -f makefile.para_data_analysis filtered_plain_trg_data_path $(PREPARE_TEST_DATA_PARAMS))
endif

prepare_test_data: $(LANG1_TEXT_SPLIT_LIST) $(LANG2_TEXT_SPLIT_LIST) $(LANG1_SEGM_DATA) $(LANG2_SEGM_DATA)
$(LANG1_TEXT_SPLIT_LIST) :
	$(MAKE) -f makefile.para_data_analysis split_data_src $(PREPARE_TEST_DATA_PARAMS)
$(LANG2_TEXT_SPLIT_LIST) :
	$(MAKE) -f makefile.para_data_analysis split_data_trg $(PREPARE_TEST_DATA_PARAMS)


SRC_TEXT_SPLIT_LIST := $(LANG1_TEXT_SPLIT_LIST)
TRG_TEXT_SPLIT_LIST := $(LANG2_TEXT_SPLIT_LIST)
SRC_SEGM_DATA := $(LANG1_SEGM_DATA)
REF_SEGM_DATA := $(LANG2_SEGM_DATA)
SRC_PLAIN_PREPROC_DATA := $(LANG1_PLAIN_PREPROC_DATA)
REF_PLAIN_PREPROC_DATA := $(LANG2_PLAIN_PREPROC_DATA)
ifneq ($(TRANSL_PAIR),$(PARA_DATA_PAIR))
SRC_TEXT_SPLIT_LIST := $(LANG2_TEXT_SPLIT_LIST)
TRG_TEXT_SPLIT_LIST := $(LANG1_TEXT_SPLIT_LIST)
SRC_SEGM_DATA := $(LANG2_SEGM_DATA)
REF_SEGM_DATA := $(LANG1_SEGM_DATA)
SRC_PLAIN_PREPROC_DATA := $(LANG2_PLAIN_PREPROC_DATA)
REF_PLAIN_PREPROC_DATA := $(LANG1_PLAIN_PREPROC_DATA)
endif

$(SRC_SEGM_DATA) : $(SRC_PLAIN_PREPROC_DATA)
$(SRC_SEGM_DATA) : LANGUAGE=$(SRC_LANG)

$(REF_SEGM_DATA) : $(REF_PLAIN_PREPROC_DATA)
$(REF_SEGM_DATA) : LANGUAGE=$(TRG_LANG)

$(SRC_SEGM_DATA) $(REF_SEGM_DATA) :
	bin/text2segm.pl --origlang $(LANGUAGE) < $< > $@

SRC_SEGM_ADJUST_DATA=$(TEST_TMP_DIR)/segm_adjust_data.src.$(SRC_LANG)
REF_SEGM_ADJUST_DATA=$(TEST_TMP_DIR)/segm_adjust_data.ref.$(TRG_LANG)

$(SRC_SEGM_ADJUST_DATA) : $(SRC_SEGM_DATA)
$(SRC_SEGM_ADJUST_DATA) : SELECTOR=src
$(SRC_SEGM_ADJUST_DATA) : LANGUAGE=$(SRC_LANG)

$(REF_SEGM_ADJUST_DATA) : $(REF_SEGM_DATA)
$(REF_SEGM_ADJUST_DATA) : SELECTOR=ref
$(REF_SEGM_ADJUST_DATA) : LANGUAGE=$(TRG_LANG)

$(SRC_SEGM_ADJUST_DATA) $(REF_SEGM_ADJUST_DATA):
	mkdir -p $(TEST_TMP_DIR)
	bin/segm_adjust.pl --language $(LANGUAGE) --selector $(SELECTOR) < $< > $@

clean_test_data :
	-$(MAKE) -f makefile.para_data_analysis clean_all $(PREPARE_TEST_DATA_PARAMS)
	-rm -rf $(TEST_TMP_DIR)
