
#========== reading variables from a config file ================
# this must be placed after all definitions of public variables

ifdef CONFIG_FILE
CONFIG_CMD:=$(shell cat $(CONFIG_FILE) | grep -v '^\#' | sed 's/ /__SPACE__/g')
$(foreach ONE_CMD,$(CONFIG_CMD),$(eval $(subst __SPACE__, ,$(ONE_CMD))))
endif
