include ../../makefile.master
include ../makefile.langpair
INPUT_SRC=../../../qtleap-corpus/references/Batch1a_en.txt
INPUT_REF=../../../qtleap-corpus/references/Batch1a_es.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-es-batch1a.txt
