include ../../makefile.master
include ../makefile.langpair
INPUT_SRC=../../../qtleap-corpus/references/Batch2q_es.txt
INPUT_REF=../../../qtleap-corpus/references/Batch2q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-es-en-batch2q.txt
