include ../../makefile.master
include ../makefile.langpair
DATASET=batch3a
INPUT_SRC=../../../qtleap-corpus/references/Batch3a_en.txt
INPUT_REF=../../../qtleap-corpus/references/Batch3a_cs.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-cs-batch3a.txt
