include ../../makefile.master
include ../makefile.langpair
DATASET=batch2q
INPUT_SRC=../../../qtleap-corpus/references/Batch2q_pt.txt
INPUT_REF=../../../qtleap-corpus/references/Batch2q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-pt-en-batch2q.txt
