include ../../makefile.master
include ../makefile.langpair
DATASET=news
INPUT_SRC=../../../qtleap-corpus/references/news_eu.txt
INPUT_REF=../../../qtleap-corpus/references/news_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-eu-en-news.txt

# ../makefile.langpair contains domain=IT, but we want to override it
SCEN=Scen::EU2EN domain=general resegment=1
