include ../../makefile.master
include ../makefile.langpair
DATASET=batch1q
INPUT_SRC=../../../qtleap-corpus/references/Batch1q_nl.txt
INPUT_REF=../../../qtleap-corpus/references/Batch1q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-nl-en-batch1q.txt
