include ../../makefile.master
include ../makefile.langpair
DATASET=news2012
INPUT_SRC=../../../qtleap-corpus/references/news2012_cs.txt
INPUT_REF=../../../qtleap-corpus/references/news2012_en.txt

# ../makefile.langpair contains domain=IT, but we want to override it
SCEN=Scen::CS2EN domain=general resegment=1
