include ../../makefile.master
include ../makefile.langpair
LINES_PER_FILE=1
JOBS=200
DATASET=batch2a_coref
INPUT_SRC=../../../qtleap-corpus/references/Batch2a_en.txt
INPUT_REF=../../../qtleap-corpus/references/Batch2a_cs.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-cs-batch2a.txt
