include ../../makefile.master
include ../makefile.langpair
DATASET=batch1a
INPUT_SRC=../../../qtleap-corpus/references/Batch1a_en.txt
INPUT_REF=../../../qtleap-corpus/references/Batch1a_nl.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-nl-batch1a.txt
