include ../../makefile.master
include ../makefile.langpair
DATASET=batch4q
INPUT_SRC=../../../qtleap-corpus/references/Batch4q_cs.txt
INPUT_REF=../../../qtleap-corpus/references/Batch4q_en.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-cs-en-batch4q.txt
