include ../../makefile.master
include ../makefile.langpair
DATASET=news
INPUT_SRC=../../../qtleap-corpus/references/news_nl.txt
INPUT_REF=../../../qtleap-corpus/references/news_en.txt

# ../makefile.langpair contains domain=IT, but we want to override it
SCEN=Scen::NL2EN domain=general resegment=1
