include ../../makefile.master
include ../makefile.langpair
DATASET=batch2a
INPUT_SRC=../../../qtleap-corpus/references/Batch2a_en.txt
INPUT_REF=../../../qtleap-corpus/references/Batch2a_nl.txt
PILOT0_FILE=../../../qtleap-corpus/pilot0/pilot0-en-nl-batch2a.txt
